# Generated by Django 5.2.7 on 2025-10-05 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa wyzwania')),
                ('description', models.TextField(verbose_name='Opis wyzwania')),
                ('target_value', models.IntegerField(verbose_name='Wartość docelowa')),
                ('attribute_to_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.attribute', verbose_name='Atrybut do sprawdzenia')),
            ],
        ),
        migrations.CreateModel(
            name='EducationalContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Treść edukacyjna')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='educational_content', to='api.question', verbose_name='Pytanie')),
            ],
        ),
    ]
