# Generated by Django 5.2.7 on 2025-10-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(max_length=50, verbose_name='Typ aktywa')),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Aktualna wartość')),
                ('acquired_at_age', models.PositiveSmallIntegerField(verbose_name='Wiek nabycia')),
                ('interest_or_growth_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='Oprocentowanie/Wzrost (%)')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_age', models.PositiveSmallIntegerField(verbose_name='Wiek rozpoczęcia')),
                ('end_age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Wiek zakończenia')),
            ],
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at_age', models.PositiveSmallIntegerField(verbose_name='Wiek wystąpienia zdarzenia')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('SPOUSE', 'Partner/Partnerka'), ('CHILD', 'Dziecko')], max_length=20, verbose_name='Typ relacji')),
                ('name', models.CharField(max_length=100, verbose_name='Imię')),
                ('birth_age', models.PositiveSmallIntegerField(verbose_name='Wiek postaci w momencie pojawienia się członka rodziny')),
            ],
        ),
    ]
