# Generated by Django 5.2.7 on 2025-10-04 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('character', '0001_initial'),
        ('game_rules', '0001_initial'),
        ('game_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterasset',
            name='game_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='game_sessions.gamesession', verbose_name='Sesja gry'),
        ),
        migrations.AddField(
            model_name='characterhistory',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_rules.educationlevel', verbose_name='Edukacja'),
        ),
        migrations.AddField(
            model_name='characterhistory',
            name='game_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='game_sessions.gamesession', verbose_name='Sesja gry'),
        ),
        migrations.AddField(
            model_name='characterhistory',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_rules.job', verbose_name='Stanowisko'),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game_rules.event', verbose_name='Zdarzenie'),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='game_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='game_sessions.gamesession', verbose_name='Sesja gry'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='game_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family', to='game_sessions.gamesession', verbose_name='Sesja gry'),
        ),
    ]
