# Generated by Django 5.2.7 on 2025-10-04 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Treść odpowiedzi')),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa atrybutu')),
            ],
        ),
        migrations.CreateModel(
            name='LifeStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa etapu')),
                ('order', models.PositiveIntegerField(help_text='Kolejność wyświetlania etapów w grze.', unique=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('+', 'Dodaj do wartości'), ('-', 'Odejmij od wartości'), ('*%', 'Modyfikuj procentowo')], max_length=2, verbose_name='Operacja')),
                ('value', models.IntegerField(verbose_name='Wartość zmiany (dla % podaj np. -10 dla -10%)')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impacts', to='game_rules.answer', verbose_name='Odpowiedź')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_rules.attribute', verbose_name='Atrybut do zmiany')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Treść pytania')),
                ('order', models.PositiveIntegerField(help_text='Kolejność pytania w ramach danego etapu życia.')),
                ('life_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='game_rules.lifestage', verbose_name='Etap życia')),
            ],
            options={
                'ordering': ['life_stage', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('>=', 'Większy lub równy'), ('<=', 'Mniejszy lub równy'), ('>', 'Większy'), ('<', 'Mniejszy'), ('==', 'Równy')], max_length=2, verbose_name='Operator porównania')),
                ('value', models.IntegerField(verbose_name='Wartość do porównania')),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='game_rules.answer')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_rules.attribute', verbose_name='Atrybut do sprawdzenia')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='game_rules.question')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='game_rules.question', verbose_name='Pytanie'),
        ),
    ]
