# Generated by Django 5.2.7 on 2025-10-04 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=100, verbose_name='Nazwa poziomu edukacji')),
                ('duration_years', models.PositiveSmallIntegerField(verbose_name='Czas trwania (w latach)')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Koszt całkowity')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nazwa zdarzenia')),
                ('description', models.TextField(verbose_name='Opis')),
                ('event_type', models.CharField(choices=[('HEALTH', 'Zdrowotne'), ('FINANCIAL', 'Finansowe'), ('FAMILY', 'Rodzinne'), ('CAREER', 'Zawodowe'), ('OPPORTUNITY', 'Okazja')], max_length=20, verbose_name='Typ zdarzenia')),
                ('health_effect', models.SmallIntegerField(default=0, verbose_name='Efekt na zdrowie')),
                ('happiness_effect', models.SmallIntegerField(default=0, verbose_name='Efekt na szczęście')),
                ('financial_effect', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Efekt finansowy')),
            ],
        ),
        migrations.CreateModel(
            name='GameScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa scenariusza')),
                ('description', models.TextField(verbose_name='Opis')),
                ('initial_age', models.PositiveSmallIntegerField(default=18, verbose_name='Wiek początkowy')),
                ('initial_cash', models.DecimalField(decimal_places=2, default=5000.0, max_digits=12, verbose_name='Początkowa gotówka')),
            ],
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa hobby')),
                ('annual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Roczny koszt')),
                ('happiness_bonus', models.SmallIntegerField(default=0, verbose_name='Bonus do szczęścia')),
                ('health_bonus', models.SmallIntegerField(default=0, verbose_name='Bonus do zdrowia')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100, verbose_name='Nazwa stanowiska')),
                ('industry', models.CharField(blank=True, max_length=100, null=True, verbose_name='Branża')),
                ('required_experience_years', models.PositiveSmallIntegerField(default=0, verbose_name='Wymagane lata doświadczenia')),
                ('gross_annual_salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Roczne zarobki brutto')),
                ('stress_impact', models.SmallIntegerField(default=0, verbose_name='Wpływ na szczęście')),
                ('health_impact', models.SmallIntegerField(default=0, verbose_name='Wpływ na zdrowie')),
                ('required_education', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_rules.educationlevel', verbose_name='Wymagana edukacja')),
            ],
        ),
    ]
